### ISSUE TITLE
Peer-to-peer code review for Jon

### ISSUE THREAD

**Issue by michael-duke** [gnuion/microverse_portfolio#5]
# Here is our feedback @gnuion 

- Refactoring is well done since, you can access your code base better.
- Semantically naming components in your css was a good choice.
- You can extend the screenshot in your README file so you can have it for all media screens.
- Really well done making the website very responsive 
- [Website Mockup Generator](https://websitemockupgenerator.com/)
-  [Multi Device Website Mockup Generator](https://techsini.com/multi-mockup/)

**Comment by gnuion** [comment]
Thank you for the suggested improvements. By merging this #6 pull request I commit those changes.
